# Site settings
name: lazybios
title: lazybios
nickname: lazybios
description: lazybios's blog
author: lazybios
twitter_username: lazybios
github_username: lazybios

# Build settings
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

IMG_PATH: http://freshstu.qiniudn.com

baseurl: ""
url: "http://lazybios.com"
permalink: /:year/:month/:title/
